use crate::domain::{OperatingRoom, OrSchedule, Surgery, TimeSlot};

pub fn demo_schedule() -> OrSchedule {
    let operating_rooms = vec![
        OperatingRoom::new(
            "or1",
            "OR-1 Cardiac".into(),
            vec!["cardiac_bypass".into(), "general".into()],
        ),
        OperatingRoom::new(
            "or2",
            "OR-2 Neuro".into(),
            vec!["neuro_monitor".into(), "general".into()],
        ),
        OperatingRoom::new(
            "or3",
            "OR-3 Ortho".into(),
            vec!["robotic_arm".into(), "general".into()],
        ),
        OperatingRoom::new("or4", "OR-4 General".into(), vec!["general".into()]),
        OperatingRoom::new("or5", "OR-5 General".into(), vec!["general".into()]),
        OperatingRoom::new(
            "or6",
            "OR-6 Hybrid".into(),
            vec![
                "cardiac_bypass".into(),
                "robotic_arm".into(),
                "general".into(),
            ],
        ),
    ];

    let time_slots = vec![
        TimeSlot::new(
            "slot1",
            "08:00".into(),
            "09:00".into(),
            vec!["surgeon1".into(), "surgeon2".into(), "surgeon3".into()],
        ),
        TimeSlot::new(
            "slot2",
            "09:00".into(),
            "10:00".into(),
            vec!["surgeon1".into(), "surgeon2".into(), "surgeon4".into()],
        ),
        TimeSlot::new(
            "slot3",
            "10:00".into(),
            "11:00".into(),
            vec!["surgeon2".into(), "surgeon3".into(), "surgeon4".into()],
        ),
        TimeSlot::new(
            "slot4",
            "11:00".into(),
            "12:00".into(),
            vec!["surgeon1".into(), "surgeon3".into(), "surgeon4".into()],
        ),
        TimeSlot::new(
            "slot5",
            "13:00".into(),
            "14:00".into(),
            vec![
                "surgeon1".into(),
                "surgeon2".into(),
                "surgeon3".into(),
                "surgeon4".into(),
            ],
        ),
        TimeSlot::new(
            "slot6",
            "14:00".into(),
            "15:00".into(),
            vec!["surgeon2".into(), "surgeon3".into(), "surgeon4".into()],
        ),
        TimeSlot::new(
            "slot7",
            "15:00".into(),
            "16:00".into(),
            vec!["surgeon1".into(), "surgeon3".into(), "surgeon4".into()],
        ),
        TimeSlot::new(
            "slot8",
            "16:00".into(),
            "17:00".into(),
            vec!["surgeon1".into(), "surgeon2".into()],
        ),
    ];

    let surgeries = vec![
        // Emergency surgeries (priority 1)
        Surgery::new(
            "s1",
            "John Smith".into(),
            "Emergency Cardiac".into(),
            120,
            vec!["cardiac_bypass".into()],
            "surgeon1".into(),
            1,
        ),
        Surgery::new(
            "s2",
            "Jane Doe".into(),
            "Emergency Trauma".into(),
            90,
            vec!["general".into()],
            "surgeon2".into(),
            1,
        ),
        // Urgent surgeries (priority 2)
        Surgery::new(
            "s3",
            "Bob Wilson".into(),
            "Urgent Appendectomy".into(),
            60,
            vec!["general".into()],
            "surgeon3".into(),
            2,
        ),
        Surgery::new(
            "s4",
            "Alice Brown".into(),
            "Urgent Fracture".into(),
            90,
            vec!["robotic_arm".into()],
            "surgeon4".into(),
            2,
        ),
        Surgery::new(
            "s5",
            "Charlie Davis".into(),
            "Urgent Neuro".into(),
            180,
            vec!["neuro_monitor".into()],
            "surgeon2".into(),
            2,
        ),
        // Elective surgeries (priority 3)
        Surgery::new(
            "s6",
            "Diana Miller".into(),
            "Knee Replacement".into(),
            120,
            vec!["robotic_arm".into()],
            "surgeon4".into(),
            3,
        ),
        Surgery::new(
            "s7",
            "Edward Jones".into(),
            "Hip Replacement".into(),
            120,
            vec!["robotic_arm".into()],
            "surgeon4".into(),
            3,
        ),
        Surgery::new(
            "s8",
            "Fiona Garcia".into(),
            "Cataract".into(),
            30,
            vec!["general".into()],
            "surgeon1".into(),
            3,
        ),
        Surgery::new(
            "s9",
            "George Martinez".into(),
            "Hernia Repair".into(),
            60,
            vec!["general".into()],
            "surgeon3".into(),
            3,
        ),
        Surgery::new(
            "s10",
            "Helen Rodriguez".into(),
            "Gallbladder".into(),
            90,
            vec!["general".into()],
            "surgeon2".into(),
            3,
        ),
        // Add more surgeries for a realistic problem
        Surgery::new(
            "s11",
            "Ian Lee".into(),
            "Cardiac Bypass".into(),
            240,
            vec!["cardiac_bypass".into()],
            "surgeon1".into(),
            2,
        ),
        Surgery::new(
            "s12",
            "Julia White".into(),
            "Brain Surgery".into(),
            300,
            vec!["neuro_monitor".into()],
            "surgeon2".into(),
            2,
        ),
        Surgery::new(
            "s13",
            "Kevin Harris".into(),
            "Spine Surgery".into(),
            180,
            vec!["robotic_arm".into()],
            "surgeon4".into(),
            3,
        ),
        Surgery::new(
            "s14",
            "Laura Clark".into(),
            "Thyroid".into(),
            90,
            vec!["general".into()],
            "surgeon3".into(),
            3,
        ),
        Surgery::new(
            "s15",
            "Michael Lewis".into(),
            "Prostate".into(),
            120,
            vec!["robotic_arm".into()],
            "surgeon4".into(),
            3,
        ),
        // More emergency cases
        Surgery::new(
            "s16",
            "Nancy Walker".into(),
            "Emergency Trauma".into(),
            90,
            vec!["general".into()],
            "surgeon1".into(),
            1,
        ),
        Surgery::new(
            "s17",
            "Oscar Young".into(),
            "Emergency Cardiac".into(),
            150,
            vec!["cardiac_bypass".into()],
            "surgeon1".into(),
            1,
        ),
        // More urgent cases
        Surgery::new(
            "s18",
            "Patricia Hall".into(),
            "Urgent Gallstone".into(),
            90,
            vec!["general".into()],
            "surgeon3".into(),
            2,
        ),
        Surgery::new(
            "s19",
            "Quinn Allen".into(),
            "Urgent Fracture".into(),
            120,
            vec!["robotic_arm".into()],
            "surgeon4".into(),
            2,
        ),
        Surgery::new(
            "s20",
            "Rachel King".into(),
            "Urgent Appendix".into(),
            60,
            vec!["general".into()],
            "surgeon2".into(),
            2,
        ),
        // More elective cases
        Surgery::new(
            "s21",
            "Samuel Wright".into(),
            "Varicose Veins".into(),
            60,
            vec!["general".into()],
            "surgeon3".into(),
            3,
        ),
        Surgery::new(
            "s22",
            "Tina Lopez".into(),
            "Cataract".into(),
            30,
            vec!["general".into()],
            "surgeon1".into(),
            3,
        ),
        Surgery::new(
            "s23",
            "Uma Hill".into(),
            "Knee Arthroscopy".into(),
            90,
            vec!["robotic_arm".into()],
            "surgeon4".into(),
            3,
        ),
        Surgery::new(
            "s24",
            "Victor Green".into(),
            "Hernia".into(),
            60,
            vec!["general".into()],
            "surgeon2".into(),
            3,
        ),
        Surgery::new(
            "s25",
            "Wendy Adams".into(),
            "Tonsillectomy".into(),
            45,
            vec!["general".into()],
            "surgeon3".into(),
            3,
        ),
        Surgery::new(
            "s26",
            "Xavier Nelson".into(),
            "Colonoscopy".into(),
            30,
            vec!["general".into()],
            "surgeon1".into(),
            3,
        ),
        Surgery::new(
            "s27",
            "Yvonne Baker".into(),
            "Breast Biopsy".into(),
            60,
            vec!["general".into()],
            "surgeon2".into(),
            3,
        ),
        Surgery::new(
            "s28",
            "Zachary Carter".into(),
            "ACL Repair".into(),
            120,
            vec!["robotic_arm".into()],
            "surgeon4".into(),
            3,
        ),
        Surgery::new(
            "s29",
            "Amy Mitchell".into(),
            "Thyroid".into(),
            90,
            vec!["general".into()],
            "surgeon3".into(),
            3,
        ),
        Surgery::new(
            "s30",
            "Brian Perez".into(),
            "Hemorrhoid".into(),
            45,
            vec!["general".into()],
            "surgeon2".into(),
            3,
        ),
    ];

    OrSchedule::new(surgeries, operating_rooms, time_slots)
}
