/* Demo data wrapper for local development.

@generated by solverforge-cli: data-wrapper v1

`solverforge generate data` rewrites the compiler-owned sample builders in
`src/generated/data_seed.rs`. Replace this wrapper only if you want to stop
using the generated seeds entirely. */

pub use crate::generated::data_seed::DemoData;

use crate::domain::Plan;

/// Generates a demo plan for the given dataset.
pub fn generate(demo: DemoData) -> Plan {
    crate::generated::data_seed::generate(demo)
}
